"""Change String size for menues

Revision ID: 6d535fc56a0c
Revises: 
Create Date: 2023-09-16 17:06:39.418069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d535fc56a0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.alter_column('room',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30),
               type_=sa.String(length=300, collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('sender',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30),
               type_=sa.String(length=300, collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    with op.batch_alter_table('menues', schema=None) as batch_op:
        batch_op.alter_column('sep',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30),
               type_=sa.String(length=300, collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('menu',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30),
               type_=sa.String(length=300, collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menues', schema=None) as batch_op:
        batch_op.alter_column('menu',
               existing_type=sa.String(length=300, collation='utf8mb4_unicode_ci'),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30),
               existing_nullable=True)
        batch_op.alter_column('sep',
               existing_type=sa.String(length=300, collation='utf8mb4_unicode_ci'),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30),
               existing_nullable=True)

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.alter_column('sender',
               existing_type=sa.String(length=300, collation='utf8mb4_unicode_ci'),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30),
               existing_nullable=True)
        batch_op.alter_column('room',
               existing_type=sa.String(length=300, collation='utf8mb4_unicode_ci'),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30),
               existing_nullable=True)

    # ### end Alembic commands ###
